### ISSUE TITLE
https://bib.ietf.org/public/rfc/bibxml-rfcsubseries/reference.BCP.0100.xml 500s

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-service#218]
https://bib.ietf.org/public/rfc/bibxml-rfcsubseries/reference.BCP.0100.xml is failing.
https://xml2rfc.tools.ietf.org/public/rfc/bibxml-rfcsubseries/reference.BCP.0100.xml returns content.

**Comment by ronaldtse** [comment]
@rjsparks thanks for reporting. @strogonoff any idea?

**Comment by rjsparks** [comment]
Also please note the feedback here: https://mailarchive.ietf.org/arch/msg/tools-discuss/Q2ELN0I1J6Y3lVWdE3xc2AoViE4

**Comment by kesara** [comment]
Here's the error log:
```
Using selector: EpollSelector
OK: /public/rfc/bibxml-rfcsubseries/reference.BCP.0100.xml
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/usr/local/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
  File "/code/xml2rfc_compat/urls.py", line 261, in handle_xml2rfc_path
    xml_repr = to_xml_string(item, anchor=requested_anchor)
  File "/code/xml2rfc_compat/serializer.py", line 22, in to_xml_string
    return serialize(item, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/relaton/serializers/bibxml_string/__init__.py", line 20, in serialize
    _original_serialize(item, **kwargs),
  File "/usr/local/lib/python3.10/site-packages/relaton/serializers/bibxml/__init__.py", line 53, in serialize
    root = create_referencegroup([
  File "/usr/local/lib/python3.10/site-packages/relaton/serializers/bibxml/reference.py", line 28, in create_referencegroup
    return E.referencegroup(*(
  File "/usr/local/lib/python3.10/site-packages/relaton/serializers/bibxml/reference.py", line 29, in <genexpr>
    create_reference(item)
  File "/usr/local/lib/python3.10/site-packages/relaton/serializers/bibxml/reference.py", line 37, in create_reference
    raise ValueError("Unable to create a <reference>: no titles")
ValueError: Unable to create a <reference>: no titles
```

**Comment by ronaldtse** [comment]
@strogonoff do you know why this is happening?

**Comment by strogonoff** [comment]
The service must hydrate “shallow” relations (fill in bibitem data when relation only has docid) within xml2rfc path handler. When it doesn’t do so, bibxml serializer fails because an “included” relation doesn’t have a title, and so a valid `<reference>` cannot be constructed for it.

The service does this hydration in GUI and main API already, xml2rfc was missing this piece.

**Comment by strogonoff** [comment]
> Also please note the feedback here: https://mailarchive.ietf.org/arch/msg/tools-discuss/Q2ELN0I1J6Y3lVWdE3xc2AoViE4

Fixed the embarrassing situation with wrong HTTP status codes for error pages (https://github.com/ietf-ribose/bibxml-service/issues/220).

**Comment by strogonoff** [comment]
Missing relation hydration logic that caused rfcsubseries (and some other) paths to fail was added. Attaching a report of all `bibxml9` paths, tested against local instance but should be equivalent live (given same data sources). 

[bibxml9-report.zip](https://github.com/ietf-ribose/bibxml-service/files/8973666/bibxml9-report.zip)

The report was produced using the xml2rfc test script at https://github.com/ietf-ribose/xml2rfc-mapping-convertor#test_pathspy.
